### PR TITLE
Edit armor_chroma.png to be closer to Vanilla's armor textures

### PR DESCRIPTION
**Pull request by Andrew6rant**
Armor, before and after

Top row is the original textures, middle row is my edit, and the bottom row is Vanilla's textures for comparison.

### CODE REVIEW

**Comment by TomSipsOnCurry** [comment]
The problem is the top row is based off the vanilla icons, not the vanilla armour.

**Comment by A5b84** [comment]
TIL forks aren't watched by default even though newly created repos are, sorry for the delay.

As @Headlessduck406 said, the current textures are based on the vanilla icons. I do prefer your edit though, so if you're interested they could be bundled in a built-in resource pack (relevant Fabric API method for future reference: [ResourceManagerHelper#registerBuiltinResourcePack](https://maven.fabricmc.net/docs/fabric-api-0.40.0+1.17/net/fabricmc/fabric/api/resource/ResourceManagerHelper.html#registerBuiltinResourcePack(net.minecraft.util.Identifier,net.fabricmc.loader.api.ModContainer,net.fabricmc.fabric.api.resource.ResourcePackActivationType))). Also if you choose to make it a separate resource pack instead, I'd happily leave a link to it in the mod description/readme if you want :)

**Comment by Andrew6rant** [comment]
You are welcome to use that asset in whatever way you want. I think a built-in resourcepack is a good idea.

**Comment by A5b84** [comment]
I've added the resource pack, thanks for the PR!

**Pull request merged**
